# Generated by Django 4.0.5 on 2022-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('image', models.TextField(default='', max_length=256)),
                ('description', models.TextField(default='', max_length=256)),
                ('price', models.CharField(default='', max_length=70)),
                ('stock', models.CharField(default='', max_length=70)),
                ('category', models.ManyToManyField(related_name='product', to='product.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
