# Generated by Django 4.0.5 on 2022-06-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
