# Generated by Django 4.0.5 on 2022-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productorder_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_complete', models.CharField(default='', max_length=70)),
                ('complete_payment', models.CharField(default='', max_length=70)),
                ('order_cancel', models.CharField(default='', max_length=70)),
                ('shipping_start', models.CharField(default='', max_length=70)),
                ('shipping_complete', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'order_statuses',
            },
        ),
    ]
