# Generated by Django 4.0.5 on 2022-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(default='', max_length=256)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('product_price', models.CharField(default='', max_length=70)),
                ('product_sale', models.CharField(default='', max_length=70)),
                ('sale_price', models.CharField(default='', max_length=70)),
                ('is_ok', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
    ]
